version: '3'

networks:
  ros:
    driver: bridge

services:
  talker:
    image: ros:ros-tutorials
    depends_on:
      - ros-master
    hostname: talker
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: rosrun roscpp_tutorials talker       
    networks:
      - ros
    restart: always

  listener:
    image: ros:ros-tutorials
    depends_on:
      - ros-master
    hostname: listener
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    command: rosrun roscpp_tutorials listener
    networks:
      - ros
    restart: always